Captcha
ThinkSpiritLab/nuist-login pull request #3
Opened 2021-10-15 03:11 UTC by fitenne

next-iron-session 实现了 Session
实现爬取登录验证码
弱密码检验

2021-10-18 20:28 UTC, A0nameless0man requested changes

2021-10-18 20:28 UTC, A0nameless0man commented on src/env.ts
> +    const name = process.env["APP_COOKIE_NAME"];
为什么从环境变量而不是配置文件读？

2021-10-18 20:28 UTC, A0nameless0man commented on src/pages/api/info.ts
> +    @MaxLength(128)
这么长？

2021-10-18 20:28 UTC, A0nameless0man commented on src/pages/index.tsx
> +    schema.is().min(8).is().max(128).has().letters().has().digits().has().not().spaces();
纯前端验证吗？

2021-10-19 01:01 UTC, fitenne commented on src/env.ts
> +    const name = process.env["APP_COOKIE_NAME"];
- 和其他配置选项保持一致

- 这个字段同样可以通过 .env.local 配置

2021-10-19 01:01 UTC, fitenne commented on src/pages/api/info.ts
> +    @MaxLength(128)
已修改为 4

2021-10-19 01:01 UTC, fitenne commented on src/pages/index.tsx
> +    schema.is().min(8).is().max(128).has().letters().has().digits().has().not().spaces();
添加后端验证。

2023-06-26 00:41 UTC, closed without merging